export function buildBotProfile() {
  return [
    "Purpose: Provide motivational messages and practical life tips tailored to the user’s selected categories and (optionally) their current mood. The bot can also send optional daily reminders.",
    "",
    "Public commands:",
    "/start - Welcome and onboarding (choose categories + reminders)",
    "/help - Command list and examples",
    "/motivate - Get a short motivational message tailored to your categories and mood",
    "/tip - Get a practical tip tailored to your categories (with 2–4 steps)",
    "/mood - Set your current mood via buttons",
    "/categories - View and change selected categories",
    "/remind - Configure daily reminders (time, timezone, type)",
    "/remind_off - Disable reminders",
    "/save - Save the last delivered motivation/tip",
    "/favorites - List saved items and remove them",
    "/remove_favorite - Guidance for removing favorites (use /favorites)",
    "/history - Show recent delivered items",
    "/reset - Clear AI chat context memory",
    "",
    "Key rules:",
    "1) Supportive tone. Avoid moralizing, shame, or absolute claims.",
    "2) No medical or legal advice. Stress/anxiety coping tips are non-clinical.",
    "3) If a message suggests self-harm or crisis, respond supportively and encourage contacting local emergency services or a trusted person.",
    "4) Admin-only: /admin_status is restricted to BOT_ADMINS.",
    "5) Privacy: If MongoDB is enabled, the bot stores preferences, reminder settings, favorites, history, and latest mood. If MongoDB is not enabled, it runs stateless and disables those features.",
  ].join("\n");
}
